<form action="guardar" method="POST" enctype="multipart/form-data" class="my-4">
    <div class="row">
        <div class="col-12">
            <div class="form-group">
                <label>Título</label>
                <input required name="nombre" type="text" class="form-control">
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-6">
            <div class="form-group">
                <label>Director</label>
                <input required name="director" type="text" class="form-control">
            </div>
        </div>
        <div class="col-2">
            <div class="form-group">
                <label>Genero</label>
                <select required name="genero" class="form-control">
                    <?php foreach($genres as $genre): ?>
                        <option value="<?= $genre->id ?>"><?= $genre->genero ?></option>
                    <?php endforeach; ?>
                </select>
            </div>
        </div>
    </div>

    <div class="form-group">
        <label>Descripcion</label>
        <textarea name="descripcion" class="form-control" rows="3" required></textarea>
    </div>

    <div class="form-group">
        <label>Imagen</label>
        <input type="file" name="imagen" id="imageToUpload" class="form-control" required>
    </div>

    <button type="submit" class="btn btn-primary mt-2">Guardar</button>
</form>